### ISSUE TITLE
These tests raise an error but the error is not listed as expected

### ISSUE THREAD

**Issue by marisademeglio** [w3c/publ-tests#27]
In the publication manifest testsuite, tests: 
* m4.2.5.01
* m4.2.5.02
* m4.2.5.03
* m6.01
* m6.02
* m6.03
* m6.04
* m6.06

and in the audiobooks testsuite, tests:
* a4.2.01
* a4.2.02
* a4.2.03
* a4.2.04
* a4.2.05

result in error that the document URL is not in the unique resources, according to [this part](https://www.w3.org/TR/pub-manifest/#processing-defaults-linking-resource) of the specification. However, this error is not listed as expected by the tests.

**Comment by iherman** [comment]
Hi @marisademeglio,

For 
- m4.2.5.01 and m4.2.5.03: I believe the right thing is to modify the example manifest by adding those references. The goal of that test suite section is to look at the URL base handling, and error message would just be besides the point
- m4.2.5.02: is a bit different because the explicit base element is set, which means that adding the URL for the test html file becomes more complicated; I have left the test as is, and did add an expected error in the test manifest. This way the situation you have described is also properly tested.
- m6.01 - m6.06: the manifests were wrong. They were not updated when we changed the file names for the test a few weeks ago... 
- a4.2.01 - a4.2.05: Like above, I believe the right thing is to modify the example manifests to be correct. 

A PR will follow on the test suite containing these changes.

(Before I forget: thanks!)
