### ISSUE TITLE
Test a4.2.05 has a description which goes against the spec

### ISSUE THREAD

**Issue by llemeurfr** [w3c/publ-tests#55]
Test [a4.2.05](https://w3c.github.io/publ-tests/test_reports/manifest_processing/#a4.2.05) has the description "There must be a TOC, either in the manifest (linked or embedded) or in the Primary Entry Page". 
This is misleading, as the spec does not make the TOC mandatory. There is only a SHOULD if supplemental content is present. 
The expected error is therefore wrong IMO ("Validation error on missing TOC")

**Comment by mattgarrish** [comment]
The bigger issue appears to be with the [manifest processing](https://w3c.github.io/audiobooks/#audio-manifest-processing) which doesn't include any nuance of supplemental resources.

But the requirement seems programmatically impossible to check reliably unless the PEP is always considered a supplemental resource. Otherwise, it requires understanding the content of the PEP, which could be anything.

**Comment by llemeurfr** [comment]
From the discussion held on #93, it appears that test a4.2.05 must be replaced by a test which guarantees that there is NO validation error if the HTML TOC is missing. 

From the test results, it appears that all processors but Thorium Reader are passing the current test => are rising a validation error if an audiobook has no TOC. The code of these processors will have to be modified I fear.

**Comment by mattgarrish** [comment]
Closing this with the changes in https://github.com/w3c/publ-tests/commit/4f8bd4c17f78e821032f55541f36eda6cac1cf6c
